Repository googleapis/java-bigquery, pull requests merged in 2020-12, with the labels that each got.

#976 docs(samples): add update iam policy for table
  samples/snippets/src/main/java/com/example/bigquery/UpdateIamPolicy.java
  samples/snippets/src/test/java/com/example/bigquery/UpdateIamPolicyIT.java
Labels: api: bigquery, cla: yes, samples

#978 docs(samples): add query materialized view
  samples/snippets/src/main/java/com/example/bigquery/QueryMaterializedView.java
  samples/snippets/src/test/java/com/example/bigquery/QueryMaterializedViewIT.java
Labels: api: bigquery, cla: yes, samples

#986 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#998 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#987 feat: set requestId for fast query path in QueryRequestInfo instead of QueryJobConfiguration
  google-cloud-bigquery/pom.xml
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryJobConfiguration.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryRequestInfo.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryRequestInfoTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
  pom.xml
Labels: api: bigquery, automerge, cla: yes

#1004 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1005 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1006 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: bigquery, cla: yes, context: full

#1008 refactor(samples): query pagination
  samples/snippets/src/main/java/com/example/bigquery/QueryPagination.java
Labels: api: bigquery, cla: yes, samples

#1013 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1014 docs(samples): add missing region tag
  samples/snippets/src/main/java/com/example/bigquery/QueryMaterializedView.java
Labels: api: bigquery, automerge, cla: yes, samples

#1016 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1021 chore: add env var for changing cloud-samples-data bucket
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: api: bigquery, cla: yes, samples

#1029 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1033 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1034 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: bigquery, automerge, cla: yes, context: full

#1036 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1037 samples: fix sample
  samples/snippets/src/main/java/com/example/bigquery/DatasetExists.java
Labels: api: bigquery, cla: yes, samples

#1041 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: bigquery, automerge, cla: yes, context: full, merge
