Repository googleapis/java-bigquery, pull requests merged in 2020-09, with the labels that each got.

#718 fix: get recordvalue by field name
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes

#719 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#726 test: fix flaky test
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: api: bigquery, cla: yes

#727 build(ci): enable auto-release in this repo
  .github/workflows/auto-release.yaml
Labels: api: bigquery, cla: yes

#729 chore: generate CODEOWNERS from templates
  .repo-metadata.json
Labels: automerge, cla: yes

#730 [CHANGE ME] Re-generated to pick up changes from self.
  .github/CODEOWNERS
  synth.metadata
Labels: cla: yes, context: none

#734 test: fix build
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: api: bigquery, cla: yes

#735 chore: comment out IT due to recent flakiness
  samples/snippets/src/test/java/com/example/bigquery/UndeleteTableIT.java
Labels: automerge, cla: yes

#732 fix: throw jobexception for invalid multiple statements query
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Job.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: api: bigquery, cla: yes, do not merge

#739 feat(bigquery): explicitly ask for dense responses from HTTP backend
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java
Labels: api: bigquery, cla: yes

#738 chore: add sync-repo-settings.yaml to grant correct access
  .github/sync-repo-settings.yaml
Labels: api: bigquery, automerge, cla: yes

#737 feat: add additional time partitioning intervals
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/TimePartitioning.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TimePartitioningTest.java
Labels: api: bigquery, cla: yes, do not merge

#745 chore(java): set yoshi-java as default CODEOWNER
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#749 feat: use bigquery exception
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Job.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes

#751 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#752 chore: remove clir
  google-cloud-bigquery/clirr-ignored-differences.xml
Labels: cla: yes

#754 fix: nullpointer exception when executionerror is null
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Job.java
Labels: cla: yes

#756 chore(ci): skip autorelease workflow on non-release PRs
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#757 docs(samples): fix flaky test case for undelete table
  samples/snippets/src/main/java/com/example/bigquery/UndeleteTable.java
  samples/snippets/src/test/java/com/example/bigquery/UndeleteTableIT.java
Labels: api: bigquery, cla: yes, samples

#758 chore(ci): verify autorelease release PR content has changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#753 test: use pages empty
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobTest.java
Labels: api: bigquery, cla: yes

#760 docs(samples): add region tag for auth snippet
  samples/snippets/src/main/java/com/example/bigquery/QueryExternalSheetsTemp.java
Labels: automerge, cla: yes

#761 build: remove maintainer permission from repo config
  .github/sync-repo-settings.yaml
Labels: cla: yes

#762 chore(java): use separate autosynth job for README
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#772 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
