Repository googleapis/java-bigquery, pull requests merged in 2020-10, with the labels that each got.

#774 docs: update clustering field docstrings
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/StandardTableDefinition.java
  samples/snippets/src/main/java/com/example/bigquery/CreateClusteredTable.java
  samples/snippets/src/main/java/com/example/bigquery/LoadTableClustered.java
Labels: cla: yes

#775 feat: add case insensitive for fields get by name
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/FieldList.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/FieldListTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: api: bigquery, cla: yes

#776 feat: add connectionId support for external data sources
  google-cloud-bigquery/clirr-ignored-differences.xml
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExternalTableDefinition.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ExternalTableDefinitionTest.java
Labels: api: bigquery, automerge, cla: yes

#781 fix: request id for fast query path
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryJobConfiguration.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryRequestInfo.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes

#763 docs(samples): add query external bigtable using temp table
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/com/example/bigquery/QueryExternalBigtableTemp.java
  samples/snippets/src/test/java/com/example/bigquery/QueryExternalBigtableTempIT.java
Labels: api: bigquery, cla: yes, samples

#785 build(java): readme.sh should be executable
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#786 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#764 docs(samples): add query external bigtable using permanent table
  samples/snippets/src/main/java/com/example/bigquery/QueryExternalBigtablePerm.java
  samples/snippets/src/test/java/com/example/bigquery/QueryExternalBigtablePermIT.java
Labels: api: bigquery, cla: yes, samples

#787 [CHANGE ME] Re-generated to pick up changes in the API or client library generator.
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, context: none

#788 fix: bigquery exception get reason and message
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryException.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes

#792 test: fix testCancelJob failed
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes

#793 fix: fix start index with page size for list rows
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes

#796 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes

#800 ci(java): suggest formatting fixes
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: bigquery, cla: yes, context: full

#803 feat: add requirePartitionFilter field in HivePartitioningOptions
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/HivePartitioningOptions.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/HivePartitioningOptionsTest.java
  pom.xml
Labels: cla: yes

#806 ci(java): restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#807 build(java): auto-approve README regeneration
  .github/workflows/approve-readme.yaml
  synth.metadata
Labels: cla: yes, context: full

#817 chore: add version property tag
  pom.xml
Labels: automerge, cla: yes

#818 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#821 docs(samples): add omni create aws dataset
  samples/snippets/src/main/java/com/example/bigquery/CreateDatasetAws.java
  samples/snippets/src/test/java/com/example/bigquery/CreateDatasetAwsIT.java
Labels: automerge, cla: yes

#822 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#804 fix: schema and totalRows for duplicate request ids
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: api: bigquery, cla: yes

#823 docs(samples): add omni create external table
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/com/example/bigquery/CreateDatasetAws.java
  samples/snippets/src/main/java/com/example/bigquery/CreateExternalTableAws.java
  samples/snippets/src/test/java/com/example/bigquery/CreateDatasetAwsIT.java
  samples/snippets/src/test/java/com/example/bigquery/CreateExternalTableAwsIT.java
Labels: automerge, cla: yes

#824 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#826 chore(deps): reorder dependencies so http-client is before storage
  google-cloud-bigquery/pom.xml
Labels: cla: yes

#827 deps: update dependency com.google.cloud:google-cloud-shared-dependencies to v0.12.1
  pom.xml
Labels: cla: yes

#829 build(java): enable snippet-bot
  .github/snippet-bot.yml
  synth.metadata
Labels: cla: yes, context: full

#837 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#839 test(deps): update dependency com.google.truth:truth to v1.1
  pom.xml
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
Labels: automerge, cla: yes

#840 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#841 chore: clean up and update renovate.json
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#844 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes

#845 ci(samples): add nightly resource cleanup
  .kokoro/nightly/samples.cfg
  .kokoro/run_samples_resource_cleanup.sh
  samples/snippets/src/main/java/com/example/bigquery/ResourceCleanUp.java
  synth.py
Labels: cla: yes

#846 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#847 refactor(samples): add clean up routines and time
  samples/snippets/src/main/java/com/example/bigquery/QueryExternalTableAws.java
  samples/snippets/src/main/java/com/example/bigquery/ResourceCleanUp.java
  samples/snippets/src/test/java/com/example/bigquery/CreateExternalTableAwsIT.java
  samples/snippets/src/test/java/com/example/bigquery/QueryExternalTableAwsIT.java
Labels: cla: yes

#850 ci(chore): comment out dataset.getCreationTime method
  samples/snippets/src/main/java/com/example/bigquery/ResourceCleanUp.java
Labels: cla: yes

#852 [CHANGE ME] Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: cla: yes, context: full

#854 ci: fix shell script "exec format error"
  .kokoro/run_samples_resource_cleanup.sh
Labels: automerge, cla: yes

#856 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#857 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#861 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#865 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#869 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#868 refactor: remove duplicate page token field from listdatasets
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java
Labels: api: bigquery, cla: yes

#866 fix(samples): dataset getcreatetime
  samples/snippets/src/main/java/com/example/bigquery/ResourceCleanUp.java
Labels: api: bigquery, cla: yes, samples

#872 ci: enable secrete manager for nightly resource cleanup
  .kokoro/nightly/samples.cfg
  .kokoro/run_samples_resource_cleanup.sh
Labels: automerge, cla: yes

#874 chore(ci): fix typo in restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#875 feat: support authorized UDF entries in dataset ACL
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Acl.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/DatasetInfo.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/AclTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/DatasetInfoTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/DatasetTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/SerializationTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes

#877 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#879 ci: prepend kokoro root directory to the path to service-acct.json
  .kokoro/run_samples_resource_cleanup.sh
Labels: automerge, cla: yes

#882 ci: update Kokoro root directory
  .kokoro/run_samples_resource_cleanup.sh
Labels: automerge, cla: yes

#884 docs(samples): fix typo
  samples/snippets/src/main/java/com/example/bigquery/ExportQueryResultsToS3.java
Labels: cla: yes

#885 ci: add one more type of table to clean up
  samples/snippets/src/main/java/com/example/bigquery/ResourceCleanUp.java
Labels: automerge, cla: yes

#889 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#890 fix: nullpointerexception for listroutines and listmodels
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes

#886 ci: nightly cleanup cleanup
  .kokoro/nightly/samples.cfg
  .kokoro/run_samples_resource_cleanup.sh
Labels: api: bigquery, automerge, cla: yes

#896 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes
