Repository googleapis/java-bigquery, pull requests merged in 2020-06, with the labels that each got.

#403 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#404 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#408 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#410 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: cla: yes, context: full

#415 docs(samples): rename extract table json to extract table csv
  samples/snippets/src/main/java/com/example/bigquery/ExtractTableToCsv.java
  samples/snippets/src/test/java/com/example/bigquery/ExtractTableToCsvIT.java
Labels: cla: yes

#416 docs(samples): added extract to json and accompanying test
  samples/snippets/src/main/java/com/example/bigquery/ExtractTableToJson.java
  samples/snippets/src/test/java/com/example/bigquery/ExtractTableToJsonIT.java
Labels: cla: yes

#417 docs(samples): adding simple query example for completeness
  samples/snippets/src/main/java/com/example/bigquery/SimpleQuery.java
  samples/snippets/src/test/java/com/example/bigquery/SimpleQueryIT.java
Labels: cla: yes

#418 docs(samples): adding destination query sample and test
  samples/snippets/src/main/java/com/example/bigquery/SaveQueryToTable.java
  samples/snippets/src/test/java/com/example/bigquery/SaveQueryToTableIT.java
Labels: automerge, cla: yes

#420 chore: turn on renovate-bot master issue for java repos
  README.md
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#423 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#424 docs(samples): add update table using dml query sample
  samples/install-without-bom/src/test/resources/userSessionsData.json
  samples/snapshot/src/test/resources/userSessionsData.json
  samples/snippets/src/main/java/com/example/bigquery/UpdateTableDML.java
  samples/snippets/src/test/java/com/example/bigquery/UpdateTableDMLIT.java
  samples/snippets/src/test/resources/userSessionsData.json
Labels: automerge, cla: yes

#422 docs(samples): adding browse table sample and test
  samples/snippets/src/main/java/com/example/bigquery/BrowseTable.java
  samples/snippets/src/test/java/com/example/bigquery/BrowseTableIT.java
Labels: cla: yes

#425 chore: run code formatter
  samples/snippets/src/main/java/com/example/bigquery/AddColumnLoadAppend.java
  samples/snippets/src/main/java/com/example/bigquery/BrowseTable.java
  samples/snippets/src/main/java/com/example/bigquery/CopyTable.java
  samples/snippets/src/main/java/com/example/bigquery/CreateClusteredTable.java
  samples/snippets/src/main/java/com/example/bigquery/CreatePartitionedTable.java
  samples/snippets/src/main/java/com/example/bigquery/ExtractTableToCsv.java
  samples/snippets/src/main/java/com/example/bigquery/ExtractTableToJson.java
  samples/snippets/src/main/java/com/example/bigquery/LoadLocalFile.java
  samples/snippets/src/main/java/com/example/bigquery/LoadParquetReplaceTable.java
  samples/snippets/src/main/java/com/example/bigquery/LoadTableClustered.java
  samples/snippets/src/main/java/com/example/bigquery/SaveQueryToTable.java
  samples/snippets/src/main/java/com/example/bigquery/SimpleQuery.java
  samples/snippets/src/main/java/com/example/bigquery/TableInsertRows.java
  samples/snippets/src/main/java/com/example/bigquery/UpdateTableDML.java
  samples/snippets/src/main/java/com/example/bigquery/UpdateTableDescription.java
  samples/snippets/src/main/java/com/example/bigquery/UpdateTableExpiration.java
  samples/snippets/src/test/java/com/example/bigquery/AddColumnLoadAppendIT.java
  samples/snippets/src/test/java/com/example/bigquery/BrowseTableIT.java
  samples/snippets/src/test/java/com/example/bigquery/CopyTableIT.java
  samples/snippets/src/test/java/com/example/bigquery/CreateClusteredTableIT.java
  samples/snippets/src/test/java/com/example/bigquery/CreatePartitionedTableIT.java
  samples/snippets/src/test/java/com/example/bigquery/ExtractTableToCsvIT.java
  samples/snippets/src/test/java/com/example/bigquery/ExtractTableToJsonIT.java
  samples/snippets/src/test/java/com/example/bigquery/LoadTableClusteredIT.java
  samples/snippets/src/test/java/com/example/bigquery/SaveQueryToTableIT.java
  samples/snippets/src/test/java/com/example/bigquery/SimpleQueryIT.java
  samples/snippets/src/test/java/com/example/bigquery/UpdateTableDMLIT.java
  samples/snippets/src/test/java/com/example/bigquery/UpdateTableDescriptionIT.java
  samples/snippets/src/test/java/com/example/bigquery/UpdateTableExpirationIT.java
Labels: automerge, cla: yes

#426 docs(samples): add load CSV from GCS sample
  samples/snippets/src/main/java/com/example/bigquery/LoadCsvFromGcs.java
  samples/snippets/src/test/java/com/example/bigquery/LoadCsvFromGcsIT.java
Labels: automerge, cla: yes

#427 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#428 docs(samples): add load CSV from GCS to overwrite table sample
  samples/snippets/src/main/java/com/example/bigquery/LoadCsvFromGcsTruncate.java
  samples/snippets/src/test/java/com/example/bigquery/LoadCsvFromGcsTruncateTest.java
Labels: automerge, cla: yes

#430 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#441 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#443 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#454 ci: switch to secret manager for samples/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#457 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#458 docs(samples): add create range partition table
  samples/snippets/src/main/java/com/example/bigquery/CreateRangePartitionedTable.java
  samples/snippets/src/test/java/com/example/bigquery/CreateRangePartitionedTableIT.java
Labels: cla: yes

#463 docs(samples): add query
  samples/snippets/src/main/java/com/example/bigquery/Query.java
  samples/snippets/src/test/java/com/example/bigquery/QueryIT.java
Labels: cla: yes

#462 docs(samples): add create and delete model
  samples/snippets/src/main/java/com/example/bigquery/CreateModel.java
  samples/snippets/src/main/java/com/example/bigquery/DeleteModel.java
  samples/snippets/src/test/java/com/example/bigquery/CreateModelIT.java
  samples/snippets/src/test/java/com/example/bigquery/DeleteModelIT.java
Labels: cla: yes

#461 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#467 refactor(samples): get model
  samples/snippets/src/test/java/com/example/bigquery/GetModelIT.java
Labels: cla: yes

#468 refactor(samples): listmodels
  samples/snippets/src/test/java/com/example/bigquery/ListModelsIT.java
Labels: cla: yes

#469 docs(samples): add query batch
  samples/snippets/src/main/java/com/example/bigquery/QueryBatch.java
  samples/snippets/src/test/java/com/example/bigquery/QueryBatchIT.java
Labels: cla: yes

#466 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#470 docs(samples): add create job
  samples/snippets/src/main/java/com/example/bigquery/CreateJob.java
  samples/snippets/src/test/java/com/example/bigquery/CreateJobIT.java
Labels: automerge, cla: yes

#473 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#477 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#479 docs(samples): add insert data types
  samples/snippets/src/main/java/com/example/bigquery/InsertingDataTypes.java
  samples/snippets/src/test/java/com/example/bigquery/InsertingDataTypesIT.java
Labels: cla: yes

#486 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#487 docs(samples): add cancel job
  samples/snippets/src/main/java/com/example/bigquery/CancelJob.java
  samples/snippets/src/test/java/com/example/bigquery/CancelJobIT.java
Labels: cla: yes

#488 docs(samples): add create table without schema
  samples/snippets/src/main/java/com/example/bigquery/CreateTableWithoutSchema.java
  samples/snippets/src/test/java/com/example/bigquery/CreateTableWithoutSchemaIT.java
Labels: cla: yes

#491 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#490 test: Improve code coverage for Acl
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/AclTest.java
  samples/snippets/src/test/java/com/example/bigquery/AddEmptyColumnIT.java
Labels: cla: yes

#492 docs(samples): add dataset exists
  samples/snippets/src/main/java/com/example/bigquery/DatasetExists.java
  samples/snippets/src/test/java/com/example/bigquery/DatasetExistsIT.java
Labels: cla: yes

#493 docs(samples): add create and delete routine
  samples/snippets/src/main/java/com/example/bigquery/CreateRoutine.java
  samples/snippets/src/main/java/com/example/bigquery/DeleteRoutine.java
  samples/snippets/src/test/java/com/example/bigquery/CreateRoutineIT.java
  samples/snippets/src/test/java/com/example/bigquery/DeleteRoutineIT.java
Labels: cla: yes

#494 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none
