Repository googleapis/java-bigquery, pull requests merged in 2020-11, with the labels that each got.

#901 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#905 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#911 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#914 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: bigquery, automerge, cla: yes, context: full

#916 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#918 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: bigquery, cla: yes, context: full

#922 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#920 refactor(samples): add nested fields
  samples/snippets/src/main/java/com/example/bigquery/ExportQueryResultsToS3.java
  samples/snippets/src/main/java/com/example/bigquery/SimpleApp.java
  samples/snippets/src/test/java/com/example/bigquery/SimpleAppIT.java
Labels: api: bigquery, cla: yes

#925 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#928 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#938 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#940 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#942 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: bigquery, cla: yes, context: full

#943 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#941 fix: make sure to fall back to old query path when query job is incomplete
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: api: bigquery, cla: yes

#947 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#954 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#956 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#957 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: bigquery, cla: yes, context: full

#959 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#961 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#703 feat: add BIGNUMERIC support
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LegacySQLTypeName.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryParameterValue.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/StandardSQLTypeName.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/FieldValueListTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryJobConfigurationTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryParameterValueTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: api: bigquery, automerge, cla: yes

#963 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: bigquery, automerge, cla: yes, context: full

#966 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#967 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#968 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: api: bigquery, automerge, cla: yes, context: full, samples

#969 docs(samples): add create external table using hivepartitioningoptions
  samples/snippets/src/main/java/com/example/bigquery/SetHivePartitioningOptions.java
  samples/snippets/src/test/java/com/example/bigquery/SetHivePartitioningOptionsIT.java
Labels: api: bigquery, cla: yes, samples

#970 docs(samples): add export model
  samples/snippets/src/main/java/com/example/bigquery/ExtractModel.java
  samples/snippets/src/test/java/com/example/bigquery/ExtractModelIT.java
Labels: api: bigquery, cla: yes, samples

#973 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#974 fix: update listPartitions() to support tables from other projects
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
Labels: api: bigquery, cla: yes

#981 test: add IT for HivePartitioningOptions
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: api: bigquery, cla: yes

#975 docs(samples): add create iam policy for table
  samples/snippets/src/main/java/com/example/bigquery/CreateIamPolicy.java
  samples/snippets/src/test/java/com/example/bigquery/CreateIamPolicyIT.java
Labels: api: bigquery, cla: yes, samples

#977 docs(samples): add create materialized view
  samples/snippets/src/main/java/com/example/bigquery/CreateMaterializedView.java
  samples/snippets/src/test/java/com/example/bigquery/CreateMaterializedViewIT.java
Labels: api: bigquery, cla: yes, samples

#982 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#983 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#979 docs(samples): add alter materialized view
  samples/snippets/src/main/java/com/example/bigquery/AlterMaterializedView.java
  samples/snippets/src/test/java/com/example/bigquery/AlterMaterializedViewIT.java
Labels: api: bigquery, cla: yes, samples

#980 docs(samples): add delete materialized view
  samples/snippets/src/main/java/com/example/bigquery/DeleteMaterializedView.java
  samples/snippets/src/test/java/com/example/bigquery/DeleteMaterializedViewIT.java
Labels: api: bigquery, cla: yes, samples

#984 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#985 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes
