Repository googleapis/java-bigquery, pull requests merged in 2020-07, with the labels that each got.

#495 docs(samples): add create routine ddl
  samples/snippets/src/main/java/com/example/bigquery/CreateRoutineDDL.java
  samples/snippets/src/test/java/com/example/bigquery/CreateRoutineDDLIT.java
Labels: cla: yes

#496 refactor: fix imports order and run code formatter
  samples/snippets/src/test/java/com/example/bigquery/AddEmptyColumnIT.java
Labels: cla: yes

#497 docs(samples): add create view
  samples/snippets/src/main/java/com/example/bigquery/CreateView.java
  samples/snippets/src/test/java/com/example/bigquery/CreateViewIT.java
Labels: cla: yes

#502 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#503 docs(samples): add get job
  samples/snippets/src/main/java/com/example/bigquery/CreateJob.java
  samples/snippets/src/main/java/com/example/bigquery/GetJob.java
  samples/snippets/src/test/java/com/example/bigquery/GetJobIT.java
Labels: cla: yes

#504 docs(samples): add get routine
  samples/snippets/src/main/java/com/example/bigquery/GetRoutine.java
  samples/snippets/src/test/java/com/example/bigquery/GetRoutineIT.java
Labels: cla: yes

#505 deps: update shared-dependencies and google-cloud-storage versions
  pom.xml
Labels: automerge, cla: yes

#507 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#508 docs(samples): add get view
  samples/snippets/src/main/java/com/example/bigquery/GetView.java
  samples/snippets/src/test/java/com/example/bigquery/GetViewIT.java
Labels: cla: yes

#510 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#511 docs(samples): add create cmek table
  samples/snippets/src/main/java/com/example/bigquery/CreateTableCMEK.java
  samples/snippets/src/test/java/com/example/bigquery/CreateTableCMEKIT.java
Labels: automerge, cla: yes

#512 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#513 docs(samples): add copy cmek table
  samples/snippets/src/main/java/com/example/bigquery/CopyTableCMEK.java
  samples/snippets/src/test/java/com/example/bigquery/CopyTableCMEKIT.java
Labels: cla: yes

#514 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#515 docs(samples): add delete label on a dataset
  samples/snippets/src/main/java/com/example/bigquery/DeleteLabelDataset.java
  samples/snippets/src/test/java/com/example/bigquery/DeleteLabelDatasetIT.java
Labels: cla: yes

#516 docs(samples): add delete label on a table
  samples/snippets/src/main/java/com/example/bigquery/DeleteLabelTable.java
  samples/snippets/src/test/java/com/example/bigquery/DeleteLabelTableIT.java
Labels: cla: yes

#522 fix: handle malformed backend responses for PolicyTag messages
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/PolicyTags.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/PolicyTagsTest.java
Labels: cla: yes

#525 refactor(samples): create a partition table
  samples/snippets/src/main/java/com/example/bigquery/CreatePartitionedTable.java
  samples/snippets/src/test/java/com/example/bigquery/CreatePartitionedTableIT.java
Labels: cla: yes

#526 docs(samples): add label dataset
  samples/snippets/src/main/java/com/example/bigquery/LabelDataset.java
  samples/snippets/src/test/java/com/example/bigquery/LabelDatasetIT.java
Labels: cla: yes

#527 docs(samples): add label table
  samples/snippets/src/main/java/com/example/bigquery/LabelTable.java
  samples/snippets/src/test/java/com/example/bigquery/LabelTableIT.java
Labels: cla: yes

#528 refactor(samples): delete a label on a dataset
  samples/snippets/src/test/java/com/example/bigquery/DeleteLabelDatasetIT.java
Labels: automerge, cla: yes

#529 refactor(samples): delete a label on a table
  samples/snippets/src/test/java/com/example/bigquery/DeleteLabelTableIT.java
Labels: cla: yes

#541 chore: fix release changelog
  CHANGELOG.md
Labels: automerge, cla: yes

#538 docs(samples): add extract compressed table
  samples/snippets/src/main/java/com/example/bigquery/ExtractTableCompressed.java
  samples/snippets/src/test/java/com/example/bigquery/ExtractTableCompressedIT.java
Labels: cla: yes

#539 docs(samples): add get dataset labels
  samples/snippets/src/main/java/com/example/bigquery/GetDatasetLabels.java
  samples/snippets/src/test/java/com/example/bigquery/GetDatasetLabelsIT.java
Labels: cla: yes

#540 docs(samples): add get table labels
  samples/snippets/src/main/java/com/example/bigquery/GetTableLabels.java
  samples/snippets/src/test/java/com/example/bigquery/GetTableLabelsIT.java
Labels: cla: yes

#544 fix(sample): region tag
  samples/snippets/src/main/java/com/example/bigquery/DeleteLabelTable.java
Labels: cla: yes

#546 docs(samples): add list routines
  samples/snippets/src/main/java/com/example/bigquery/ListRoutines.java
  samples/snippets/src/test/java/com/example/bigquery/ListRoutinesIT.java
Labels: cla: yes

#550 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#553 Correcting comment
  samples/snippets/src/main/java/com/example/bigquery/LoadCsvFromGcs.java
Labels: cla: yes

#555 docs(samples): add list dataset by label
  samples/snippets/src/main/java/com/example/bigquery/ListDatasetsByLabel.java
  samples/snippets/src/test/java/com/example/bigquery/ListDatasetsByLabelIT.java
Labels: cla: yes

#554 docs(samples): add list jobs
  samples/snippets/src/main/java/com/example/bigquery/ListJobs.java
  samples/snippets/src/test/java/com/example/bigquery/ListJobsIT.java
Labels: cla: yes

#557 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#558 docs(samples): add create view ddl
  samples/snippets/src/main/java/com/example/bigquery/DDLCreateView.java
  samples/snippets/src/test/java/com/example/bigquery/DDLCreateViewIT.java
Labels: cla: yes

#478 docs(samples): add auth user flow and query
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/com/example/bigquery/AuthUserFlow.java
  samples/snippets/src/main/java/com/example/bigquery/AuthUserQuery.java
Labels: cla: yes

#562 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#563 docs(samples): add grant view access
  samples/snippets/src/main/java/com/example/bigquery/GrantViewAccess.java
  samples/snippets/src/test/java/com/example/bigquery/GrantViewAccessIT.java
Labels: cla: yes

#564 docs(samples): add load table from gcs using avro file
  samples/snippets/src/main/java/com/example/bigquery/LoadAvroFromGCS.java
  samples/snippets/src/test/java/com/example/bigquery/LoadAvroFromGCSIT.java
Labels: cla: yes

#566 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#569 docs(samples): add load json file from gcs into a table with autodetect schema
  samples/snippets/src/main/java/com/example/bigquery/LoadJsonFromGCSAutodetect.java
  samples/snippets/src/test/java/com/example/bigquery/LoadJsonFromGCSAutodetectIT.java
Labels: cla: yes

#570 docs(samples): add region tag for oauth dependencies
  samples/snippets/pom.xml
Labels: automerge, cla: yes

#571 chore: fix tag
  samples/snippets/pom.xml
Labels: automerge, cla: yes

#572 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#574 refactor(samples): insert rows into a table
  samples/snippets/src/main/java/com/example/bigquery/TableInsertRows.java
  samples/snippets/src/test/java/com/example/bigquery/TableInsertRowsIT.java
Labels: cla: yes

#575 docs(samples): add load json table with encryption key from gcs
  samples/snippets/src/main/java/com/example/bigquery/LoadJsonFromGCSCMEK.java
  samples/snippets/src/test/java/com/example/bigquery/LoadJsonFromGCSCMEKIT.java
Labels: cla: yes

#576 docs(samples): add query destination table with encryption key
  samples/snippets/src/main/java/com/example/bigquery/QueryDestinationTableCMEK.java
  samples/snippets/src/test/java/com/example/bigquery/QueryDestinationTableCMEKIT.java
Labels: cla: yes

#573 docs(samples): add insert rows without rowids in a table
  samples/snippets/src/main/java/com/example/bigquery/TableInsertRowsWithoutRowIds.java
  samples/snippets/src/test/java/com/example/bigquery/TableInsertRowsWithoutRowIdsIT.java
Labels: automerge, cla: yes

#578 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#581 refactor(samples): load csv table from gcs
  samples/snippets/src/main/java/com/example/bigquery/LoadCsvFromGcs.java
  samples/snippets/src/test/java/com/example/bigquery/LoadCsvFromGcsIT.java
Labels: cla: yes

#583 docs(samples): load orc file into a table from gcs
  samples/snippets/src/main/java/com/example/bigquery/LoadOrcFromGCS.java
  samples/snippets/src/test/java/com/example/bigquery/LoadOrcFromGCSIT.java
Labels: cla: yes

#582 docs(samples): add load json table with overwrite data from gcs
  samples/snippets/src/main/java/com/example/bigquery/LoadJsonFromGCSTruncate.java
  samples/snippets/src/test/java/com/example/bigquery/LoadJsonFromGCSTruncateIT.java
Labels: cla: yes

#584 docs(samples): add load orc file and overwrite data into a table from gcs
  samples/snippets/src/main/java/com/example/bigquery/LoadOrcFromGcsTruncate.java
  samples/snippets/src/test/java/com/example/bigquery/LoadOrcFromGcsTruncateIT.java
Labels: automerge, cla: yes

#586 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#587 docs(samples): add query dry run
  samples/snippets/src/main/java/com/example/bigquery/QueryDryRun.java
  samples/snippets/src/test/java/com/example/bigquery/QueryDryRunIT.java
Labels: cla: yes

#588 docs(samples): add query on external table from gcs
  samples/snippets/src/main/java/com/example/bigquery/QueryExternalGCSPerm.java
  samples/snippets/src/test/java/com/example/bigquery/QueryExternalGCSPermIT.java
Labels: cla: yes

#592 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#595 docs(samples): add query disable cache
  samples/snippets/src/main/java/com/example/bigquery/QueryDisableCache.java
  samples/snippets/src/test/java/com/example/bigquery/QueryDisableCacheIT.java
Labels: cla: yes

#593 docs(samples): add query on external temp table from gcs
  samples/snippets/src/main/java/com/example/bigquery/QueryExternalGCSTemp.java
  samples/snippets/src/test/java/com/example/bigquery/QueryExternalGCSTempIT.java
Labels: cla: yes

#594 docs(samples): add query legacy large results
  samples/snippets/src/main/java/com/example/bigquery/QueryLargeResults.java
  samples/snippets/src/test/java/com/example/bigquery/QueryLargeResultsIT.java
Labels: cla: yes

#596 docs(samples): add query pagination
  samples/snippets/src/main/java/com/example/bigquery/QueryPagination.java
  samples/snippets/src/test/java/com/example/bigquery/QueryPaginationIT.java
Labels: cla: yes

#597 docs(samples): add query partitioned table
  samples/snippets/src/main/java/com/example/bigquery/QueryPartitionedTable.java
  samples/snippets/src/test/java/com/example/bigquery/QueryPartitionedTableIT.java
Labels: cla: yes

#600 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#603 docs(samples): add query with arrays parameters
  samples/snippets/src/main/java/com/example/bigquery/QueryWithArrayParameters.java
  samples/snippets/src/test/java/com/example/bigquery/QueryWithArrayParametersIT.java
Labels: cla: yes

#604 docs(samples): add query with timestamp parameters
  samples/snippets/src/main/java/com/example/bigquery/QueryWithTimestampParameters.java
  samples/snippets/src/test/java/com/example/bigquery/QueryWithTimestampParametersIT.java
Labels: cla: yes

#605 docs(samples): add query script
  samples/snippets/src/main/java/com/example/bigquery/QueryScript.java
  samples/snippets/src/test/java/com/example/bigquery/QueryScriptIT.java
Labels: cla: yes

#607 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#609 docs(samples): add query total rows
  samples/snippets/src/main/java/com/example/bigquery/QueryTotalRows.java
  samples/snippets/src/test/java/com/example/bigquery/QueryTotalRowsIT.java
Labels: cla: yes

#610 docs(samples): add table exists
  samples/snippets/src/main/java/com/example/bigquery/TableExists.java
  samples/snippets/src/test/java/com/example/bigquery/TableExistsIT.java
Labels: cla: yes

#612 docs(samples): add update dataset partition expiration
  samples/snippets/src/main/java/com/example/bigquery/UpdateDatasetPartitionExpiration.java
  samples/snippets/src/test/java/com/example/bigquery/UpdateDatasetPartitionExpirationIT.java
Labels: cla: yes

#615 chore: regenerate samples list
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#611 docs(samples): add undelete table
  samples/snippets/src/main/java/com/example/bigquery/UndeleteTable.java
  samples/snippets/src/test/java/com/example/bigquery/UndeleteTableIT.java
Labels: cla: yes, kokoro:force-run

#616 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#620 revert: "docs(samples): add undelete table"
  samples/snippets/src/main/java/com/example/bigquery/UndeleteTable.java
  samples/snippets/src/test/java/com/example/bigquery/UndeleteTableIT.java
Labels: cla: yes

#617 docs(samples): add update model description
  samples/snippets/src/main/java/com/example/bigquery/UpdateModelDescription.java
  samples/snippets/src/test/java/com/example/bigquery/UpdateModelDescriptionIT.java
Labels: cla: yes

#621 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#619 docs(samples): add update table cmek
  samples/snippets/src/main/java/com/example/bigquery/UpdateTableCMEK.java
  samples/snippets/src/test/java/com/example/bigquery/UpdateTableCMEKIT.java
Labels: cla: yes

#623 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#622 refactor(samples): load clustered table
  samples/snippets/src/main/java/com/example/bigquery/LoadTableClustered.java
  samples/snippets/src/test/java/com/example/bigquery/LoadTableClusteredIT.java
Labels: cla: yes

#618 docs(samples): add update routine
  samples/snippets/src/main/java/com/example/bigquery/UpdateRoutine.java
  samples/snippets/src/test/java/com/example/bigquery/UpdateRoutineIT.java
Labels: cla: yes

#624 docs(samples): add update table require partition filter
  samples/snippets/src/test/java/com/example/bigquery/UpdateTableRequirePartitionFilter.java
  samples/snippets/src/test/java/com/example/bigquery/UpdateTableRequirePartitionFilterIT.java
Labels: cla: yes

#625 docs(samples): update view query
  samples/snippets/src/main/java/com/example/bigquery/UpdateViewQuery.java
  samples/snippets/src/test/java/com/example/bigquery/UpdateViewQueryIT.java
Labels: cla: yes

#629 docs(samples): add delete dataset and contents
  samples/snippets/src/main/java/com/example/bigquery/DeleteDatasetAndContents.java
  samples/snippets/src/test/java/com/example/bigquery/DeleteDatasetAndContentsIT.java
Labels: cla: yes

#627 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none
