Repository googleapis/java-bigquery, pull requests merged in 2020-08, with the labels that each got.

#633 docs(samples): add query with name types parameters
  samples/snippets/src/main/java/com/example/bigquery/QueryWithNamedTypesParameters.java
  samples/snippets/src/test/java/com/example/bigquery/QueryWithNamedTypesParametersIT.java
Labels: cla: yes

#634 docs(samples): add query with positional type parameters
  samples/snippets/src/main/java/com/example/bigquery/QueryWithPositionalTypesParameters.java
  samples/snippets/src/test/java/com/example/bigquery/QueryWithPositionalTypesParametersIT.java
Labels: cla: yes

#632 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#636 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#637 docs(samples): add authorized view tutorial
  samples/snippets/src/main/java/com/example/bigquery/AuthorizedViewTutorial.java
  samples/snippets/src/test/java/com/example/bigquery/AuthorizedViewTutorialIT.java
Labels: cla: yes

#642 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#646 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#644 refactor(samples): add column load append
  samples/snippets/src/main/java/com/example/bigquery/AddColumnLoadAppend.java
  samples/snippets/src/test/java/com/example/bigquery/AddColumnLoadAppendIT.java
Labels: cla: yes

#638 docs(samples): add undelete table
  samples/snippets/src/main/java/com/example/bigquery/UndeleteTable.java
  samples/snippets/src/test/java/com/example/bigquery/UndeleteTableIT.java
Labels: cla: yes

#648 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#651 docs(samples): fix region tag for bigquery_relax_column_query_append
  samples/snippets/src/main/java/com/example/bigquery/RelaxTableQuery.java
Labels: automerge, cla: yes

#655 docs(samples): add load csv autodetect data from gcs
  samples/snippets/src/main/java/com/example/bigquery/LoadCsvFromGCSAutodetect.java
  samples/snippets/src/test/java/com/example/bigquery/LoadCsvFromGCSAutodetectIT.java
Labels: cla: yes

#652 build: update dependencies check to only check for runtime and compile scopes
  .kokoro/dependencies.sh
  synth.metadata
Labels: cla: yes, context: full

#659 docs(samples): add query external sheet temp table
  samples/snippets/src/main/java/com/example/bigquery/QueryExternalSheetsTemp.java
  samples/snippets/src/test/java/com/example/bigquery/QueryExternalSheetsTempIT.java
Labels: cla: yes

#658 docs(samples): add query external sheet permanent table
  samples/snippets/src/main/java/com/example/bigquery/QueryExternalSheetsPerm.java
  samples/snippets/src/test/java/com/example/bigquery/QueryExternalSheetsPermIT.java
Labels: cla: yes

#662 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#657 docs(samples): add relax column load append
  samples/snippets/src/main/java/com/example/bigquery/RelaxColumnLoadAppend.java
  samples/snippets/src/test/java/com/example/bigquery/RelaxColumnLoadAppendIT.java
Labels: cla: yes

#666 docs: remove outdated readme content
  .readme-partials.yaml
Labels: automerge, cla: yes

#668 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#667 docs: update samples README.md
  samples/README.md
Labels: cla: yes

#674 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#676 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#678 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#684 [CHANGE ME] Re-generated to pick up changes from synthtool.
  .github/workflows/samples.yaml
  README.md
  synth.metadata
Labels: cla: yes, context: partial

#653 feat: support for Table ACLs
  google-cloud-bigquery/clirr-ignored-differences.xml
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Acl.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQuery.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryOptions.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/PolicyHelper.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/TableId.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/BigQueryRpc.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/PolicyHelperTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TableIdTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: api: bigquery, cla: yes

#686 feat: add jmh benchmark module
  benchmark/README.md
  benchmark/pom.xml
  benchmark/src/main/java/com.google.cloud.bigquery/QueryBenchmark.java
  pom.xml
Labels: cla: yes

#691 build: skip benchmark module in release artifact publishing
  benchmark/pom.xml
Labels: automerge, cla: yes

#692 fix: temporarily disable reporting to unblock releases
  .kokoro/release/stage.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#693 chore: benchmark README.md updates
  benchmark/README.md
Labels: api: bigquery, cla: yes

#699 fix: npe for destination table
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Job.java
Labels: cla: yes

#702 build: switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  README.md
  synth.metadata
Labels: cla: yes, context: partial

#704 ci: lower codecov baseline
  codecov.yaml
Labels: cla: yes

#707 ci: ignore codecov file
  synth.py
Labels: automerge, cla: yes

#713 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#714 chore: update google-cloud-bigquery-parent version in benchmark pom during release
  benchmark/pom.xml
Labels: automerge, cla: yes
