Repository googleapis/java-bigquery, pull requests merged in 2020-05, with the labels that each got.

#305 fix: null type in timepartitioning.
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/StandardTableDefinition.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/TimePartitioning.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/StandardTableDefinitionTest.java
Labels: cla: yes

#315 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#320 feat: add support connection properties for job and query
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ConnectionProperty.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryJobConfiguration.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ConnectionPropertyTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryJobConfigurationTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes

#321 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#323 feat: switch to use java-shared-deps
  google-cloud-bigquery/pom.xml
  pom.xml
Labels: cla: yes

#328 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#336 feat: add hourly partitioning support
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/TimePartitioning.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TimePartitioningTest.java
Labels: automerge, cla: yes

#227 feat: add extract model for extractjobconfiguration
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExtractJobConfiguration.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ExtractJobConfigurationTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: automerge, cla: yes

#341 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#344 ci: enable Github actions - no conflict
  .github/workflows/ci.yaml
  .kokoro/build.bat
  synth.metadata
Labels: cla: yes

#347 feat: add labels for writechannelconfiguration
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/WriteChannelConfiguration.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/WriteChannelConfigurationTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes

#355 chore: bump dep post release
  README.md
  synth.metadata
Labels: cla: yes, context: none

#360 docs(samples): Added UpdateTableDescription example.
  samples/snippets/src/main/java/com/example/bigquery/UpdateTableDescription.java
  samples/snippets/src/test/java/com/example/bigquery/UpdateTableDescriptionIT.java
Labels: cla: yes

#363 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#364 chore: remove hamcrest dependency and modify test case
  google-cloud-bigquery/pom.xml
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/StandardTableDefinition.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/StandardTableDefinitionTest.java
Labels: cla: yes

#348 chore: add mockitto dependency and convert test cases
  google-cloud-bigquery/pom.xml
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryExceptionTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryOptionsTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/DatasetTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ModelTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/RoutineTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TableDataWriteChannelTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TableTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/testing/RemoteBigQueryHelperTest.java
  pom.xml
Labels: cla: yes

#371 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#372 fix: error message for get routine
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
Labels: cla: yes

#370 feat: remove autovalue profile as it has moved to shared-config
  google-cloud-bigquery/EnableAutoValue.txt
  pom.xml
Labels: cla: yes

#377 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#378 chore(java): allow overriding minimum supported Java version in templates (#577)
  README.md
  synth.metadata
Labels: cla: yes, context: partial

#379 docs(samples): Include clustering fields and schema in CreateClusteredTable as part of the function arguments
  samples/snippets/src/main/java/com/example/bigquery/CreateClusteredTable.java
  samples/snippets/src/test/java/com/example/bigquery/CreateClusteredTableIT.java
Labels: cla: yes

#383 chore: remove objenesis ignore from maven dependency plugin
  pom.xml
Labels: cla: yes

#382 docs(samples): Include clustering fields and schema in LoadTableClusteredIT as part of the function arguments
  samples/snippets/src/main/java/com/example/bigquery/LoadTableClustered.java
  samples/snippets/src/test/java/com/example/bigquery/LoadTableClusteredIT.java
Labels: cla: yes

#384 chore(java): fix inadvertent whitespace changes (#578)
  README.md
  synth.metadata
Labels: cla: yes, context: full

#386 docs(samples): Convert tightly coupled local variable inside of method into method arguments
  samples/snippets/src/main/java/com/example/bigquery/AddColumnLoadAppend.java
  samples/snippets/src/main/java/com/example/bigquery/LoadParquet.java
  samples/snippets/src/main/java/com/example/bigquery/LoadParquetReplaceTable.java
  samples/snippets/src/main/java/com/example/bigquery/TableInsertRows.java
  samples/snippets/src/main/java/com/example/bigquery/UpdateDatasetAccess.java
  samples/snippets/src/main/java/com/example/bigquery/UpdateDatasetExpiration.java
  samples/snippets/src/main/java/com/example/bigquery/UpdateTableExpiration.java
  samples/snippets/src/test/java/com/example/bigquery/AddColumnLoadAppendIT.java
  samples/snippets/src/test/java/com/example/bigquery/LoadParquetIT.java
  samples/snippets/src/test/java/com/example/bigquery/LoadParquetReplaceTableIT.java
  samples/snippets/src/test/java/com/example/bigquery/TableInsertRowsIT.java
  samples/snippets/src/test/java/com/example/bigquery/UpdateDatasetAccessIT.java
  samples/snippets/src/test/java/com/example/bigquery/UpdateDatasetExpirationIT.java
  samples/snippets/src/test/java/com/example/bigquery/UpdateTableExpirationIT.java
Labels: automerge, cla: yes

#390 deps: update shared-deps and add back certain test deps
  pom.xml
Labels: cla: yes

#393 docs(samples): Convert tightly coupled local variable involved options inside of method into method arguments
  samples/snippets/src/main/java/com/example/bigquery/CreatePartitionedTable.java
  samples/snippets/src/main/java/com/example/bigquery/ExtractTableToJson.java
  samples/snippets/src/main/java/com/example/bigquery/LoadLocalFile.java
  samples/snippets/src/test/java/com/example/bigquery/CreatePartitionedTableIT.java
  samples/snippets/src/test/java/com/example/bigquery/ExtractTableToJsonIT.java
  samples/snippets/src/test/java/com/example/bigquery/LoadLocalFileIT.java
Labels: automerge, cla: yes

#395 chore: cover code coverage
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigtableOptionsTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ExternalTableDefinitionTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/LoadJobConfigurationTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ModelTableDefinitionTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/PolicyTagsTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryJobConfigurationTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryParameterValueTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryStageTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/RoutineInfoTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/StandardTableDefinitionTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TableTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TimePartitioningTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TimelineSampleTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ViewDefinitionTest.java
Labels: automerge, cla: yes, kokoro:force-run

#397 docs(samples): Fix flaky test
  samples/snippets/src/test/java/com/example/bigquery/UpdateTableExpirationIT.java
Labels: cla: yes

#401 docs(samples): update revierwers for samples module changes
  .github/CODEOWNERS
Labels: automerge, cla: yes

#402 deps: restrict -annotation deps
  google-cloud-bigquery/pom.xml
  pom.xml
Labels: automerge, cla: yes
