Repository googleapis/java-bigquery, pull requests merged in 2021-07, with the labels that each got.

#1427 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1434 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1431 feat: add dmlStatistics support
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/DmlStats.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/JobStatistics.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/DmlStatsTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobStatisticsTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: api: bigquery, automerge, cla: yes

#1436 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1440 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1441 chore: remove All rights reserved clause from java.header
  java.header
  synth.metadata
Labels: api: bigquery, cla: yes, context: full

#1442 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1426 feat: Implemented BigQueryRetryAlgorithm to retry on the basis of the configured re-triable error messages
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryErrorMessages.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryException.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryRetryAlgorithm.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryRetryConfig.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryRetryHelper.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Job.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
Labels: api: bigquery, cla: yes

#1450 chore: update dependencyDashboard labels
  renovate.json
Labels: api: bigquery, automerge, cla: yes

#1447 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1451 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1457 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes, kokoro:force-run

#1463 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes
