Repository googleapis/java-bigquery, pull requests merged in 2021-01, with the labels that each got.

#1048 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1050 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1053 samples: Fixes #1051
  samples/snippets/src/main/java/com/example/bigquery/UpdateViewQuery.java
Labels: api: bigquery, automerge, cla: yes, samples

#1060 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1066 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1071 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1073 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1078 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: bigquery, automerge, cla: yes, context: full

#1080 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: bigquery, automerge, cla: yes

#1082 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes
