Repository googleapis/java-bigquery, pull requests merged in 2021-05, with the labels that each got.

#1276 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1277 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1279 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: bigquery, automerge, cla: yes, context: none

#1278 feat: add support for user defined TVFs
  google-cloud-bigquery/clirr-ignored-differences.xml
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Routine.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/RoutineInfo.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/StandardSQLTableType.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/RoutineTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/StandardSQLTableTypeTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: api: bigquery, automerge, cla: yes

#1287 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1298 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1307 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: bigquery, automerge, cla: yes, context: full

#1301 feat: add support for partitioning and clustering in MaterializedViewDefinition
  google-cloud-bigquery/clirr-ignored-differences.xml
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/MaterializedViewDefinition.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/MaterializedViewDefinitionTest.java
Labels: api: bigquery, automerge, cla: yes

#1312 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1316 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1317 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: bigquery, automerge, cla: yes, context: full

#1318 feat: add ParquetOptions support and expose it in LoadJobConfiguration and ExternalTableDefinition classes
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExternalTableDefinition.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/FormatOptions.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LoadJobConfiguration.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ParquetOptions.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ParquetOptionsTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: api: bigquery, cla: yes

#1325 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1330 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1331 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: bigquery, automerge, cla: yes, context: full

#1335 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: bigquery, automerge, cla: yes, context: full

#1338 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes
