Repository googleapis/java-bigquery, pull requests merged in 2021-08, with the labels that each got.

#1468 chore: fix checker-qual dependency issue
  pom.xml
Labels: api: bigquery, automerge, cla: yes

#1470 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: bigquery, automerge, cla: yes

#1471 chore: configure initial java7 version
  .github/workflows/ci.yaml
Labels: api: bigquery, cla: yes

#1465 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: bigquery, cla: yes, context: full

#1476 ci: remove Java 7 branch protection
  .github/sync-repo-settings.yaml
Labels: api: bigquery, automerge, cla: yes

#1480 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigquery, automerge

#1484 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigquery, automerge

#1485 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigquery, automerge

#1493 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigquery, automerge

#1499 feat: Updated `BigQueryRetryAlgorithm` so that it can retry on RateLimit Errors using RegEx
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryErrorMessages.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryRetryAlgorithm.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryRetryConfig.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
Labels: cla: yes, api: bigquery

#1497 feat: add support for transactioninfo in query statistics
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/JobStatistics.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobStatisticsTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes, api: bigquery, automerge

#1501 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  synth.metadata
Labels: cla: yes, api: bigquery, context: full

#1502 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigquery, automerge

#1503 deps: update dependency com.google.cloud:google-cloud-shared-dependencies to v2.0.1
  pom.xml
Labels: cla: yes, api: bigquery, automerge

#1506 fix: add retry logging for BigQueryRetryAlgorithm.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryRetryAlgorithm.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryRetryHelper.java
Labels: cla: yes, api: bigquery

#1508 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigquery, automerge

#1513 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: bigquery, automerge

#1514 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigquery, automerge

#1530 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigquery, automerge

#1531 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigquery, automerge

#1548 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigquery, automerge
