Repository googleapis/java-bigquery, pull requests merged in 2021-09, with the labels that each got.

#1553 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigquery, automerge

#1562 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigquery, automerge

#1564 chore(java): install maven 3.8.1 at runtime
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: bigquery, context: partial

#1569 chore(java): update windows build
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: bigquery, context: full

#1573 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigquery, automerge

#1576 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, kokoro:force-run, api: bigquery, automerge

#1578 chore(java): update shared-config and shared-dependencies version in pom template
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  synth.metadata
Labels: cla: yes, api: bigquery, context: full

#1579 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py.py
Labels: cla: yes, api: bigquery

#1581 chore: add UUID to retry logging
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryRetryAlgorithm.java
Labels: cla: yes, api: bigquery, automerge

#1596 fix: do not throw NPE from BigQueryImpl.testIamPermissions
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
Labels: cla: yes, api: bigquery, automerge

#1599 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: bigquery

#1604 fix: add retrySetting in logging
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryRetryHelper.java
Labels: cla: yes, api: bigquery, automerge

#1623 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: bigquery

#1625 chore: change branch master to main in github configurations
  .github/blunderbuss.yml
  .github/workflows/ci.yaml
  README.md
Labels: cla: yes, api: bigquery, automerge
