Repository googleapis/java-bigquery, pull requests merged in 2021-03, with the labels that each got.

#1155 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: bigquery, automerge, cla: yes, context: full

#1158 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1162 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1163 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: bigquery, cla: yes, context: full

#1170 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1172 build(java): update autorelease title check in response to the new multi release branch changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: bigquery, automerge, cla: yes, context: full

#1179 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1183 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1189 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1191 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1194 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1198 chore(java): detect sample-secrets in build.sh
  .kokoro/build.sh
  synth.metadata
Labels: api: bigquery, automerge, build.sh, cla: yes, context: full, in, sample-secrets, samples

#1199 chore(ci): xml namespace declaration in samples/snippets/pom.xml
  samples/snippets/pom.xml
Labels: api: bigquery, cla: yes, samples

#1203 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1205 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1206 chore: remove staging bucket v2
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: bigquery, automerge, cla: yes, context: full

#1209 docs(samples): update querypagination sample
  samples/snippets/src/main/java/com/example/bigquery/QueryPagination.java
Labels: api: bigquery, automerge, cla: yes, samples
