Repository googleapis/java-bigquery, pull requests merged in 2021-02, with the labels that each got.

#1084 chore: Re-generated to pick up changes from self.
  .kokoro/build.sh
  synth.metadata
Labels: api: bigquery, cla: yes, context: none

#1085 chore: Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: bigquery, cla: yes, context: partial

#1086 docs(samples): fix sample issue
  samples/snippets/src/main/java/com/example/bigquery/ExtractTableToJson.java
  samples/snippets/src/test/java/com/example/bigquery/ExtractTableToJsonIT.java
Labels: api: bigquery, automerge, cla: yes, samples

#1089 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/build.sh
  .kokoro/linkage-monitor.sh
  synth.metadata
Labels: api: bigquery, cla: yes, context: partial

#1091 build(java): update autorelease branch name check
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: bigquery, automerge, cla: yes, context: full

#1092 chore: Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: automerge, cla: yes, context: full

#1018 feat: add reservation usage in job statistics
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/JobStatistics.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobStatisticsTest.java
Labels: api: bigquery, cla: yes

#1097 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1094 feat: add support for javascript UDFs determinism level
  google-cloud-bigquery/clirr-ignored-differences.xml
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Routine.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/RoutineInfo.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/RoutineInfoTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/RoutineTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: api: bigquery, automerge, cla: yes

#1100 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1107 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1113 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1114 [CHANGE ME] Re-generated to pick up changes from self.
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: bigquery, cla: yes, context: none

#1115 [CHANGE ME] Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: bigquery, cla: yes, context: partial

#1117 [CHANGE ME] Re-generated to pick up changes from self.
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: bigquery, cla: yes, context: none

#1120 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: bigquery, automerge, cla: yes, context: full

#1123 chore: resource cleanup for new bigquerystorage samples testing
  samples/snippets/src/main/java/com/example/bigquery/ResourceCleanUp.java
Labels: api: bigquery, automerge, cla: yes, samples

#1127 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1135 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1137 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1139 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1146 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes
