Repository googleapis/java-bigquery, pull requests merged in 2021-06, with the labels that each got.

#1352 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1358 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1363 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1364 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1345 feat: add support for DecimalTargetTypes
  google-cloud-bigquery/clirr-ignored-differences.xml
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExternalTableDefinition.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LoadJobConfiguration.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ExternalTableDefinitionTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/LoadJobConfigurationTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: api: bigquery, cla: yes

#1367 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1370 fix: handle specific exceptions
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryBaseService.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
Labels: api: bigquery, cla: yes

#1378 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1379 fix: bug fix for get method of Bigquery Dataset
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Dataset.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/DatasetTest.java
Labels: api: bigquery, cla: yes

#1381 chore: minimize noise from build scripts
  .kokoro/coerce_logs.sh
  synth.metadata
Labels: api: bigquery, cla: yes, context: full

#1386 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1389 docs(sample): update UpdateTableExpiration sample
  samples/snippets/src/main/java/com/example/bigquery/UpdateTableExpiration.java
Labels: api: bigquery, automerge, cla: yes, samples

#1387 feat: add support for jobs.delete
  google-cloud-bigquery/clirr-ignored-differences.xml
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQuery.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/BigQueryRpc.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: api: bigquery, cla: yes

#1390 feat: add support for parameterized type
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Field.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/SchemaTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: api: bigquery, automerge, cla: yes

#1393 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1320 feat: add support for table snapshot
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/CopyJobConfiguration.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/SnapshotTableDefinition.java
  google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/TableDefinition.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/CopyJobConfigurationTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/SnapshotTableDefinitionTest.java
  google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: api: bigquery, cla: yes

#1397 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1404 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1408 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1410 ci: remove self-managed distributionManagement
  pom.xml
Labels: api: bigquery, automerge, cla: yes

#1419 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes

#1420 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquery, automerge, cla: yes
